#include <stdio.h>
#include <stdbool.h>

/*
 * Round Robin CPU Scheduling Algorithm using user-defined functions
  * This program calculates waiting time, turnaround time, and average times
   * for a set of processes based on arrival times and burst times,
    * using a given time quantum.
     */

     void inputData(int n, int arrival[], int burst[], int *timeQuantum);
     void roundRobinScheduling(int n, int arrival[], int burst[], int timeQuantum, int completion[]);
     void calculateTimes(int n, int arrival[], int burst[], int completion[], int waiting[], int turnaround[]);
     void displayResults(int n, int arrival[], int burst[], int completion[], int waiting[], int turnaround[]);

     int main() {
         int n, timeQuantum;
             printf("Enter the number of processes: ");
                 scanf("%d", &n);

                     int arrival[n], burst[n], completion[n];
                         int waiting[n], turnaround[n];

                             inputData(n, arrival, burst, &timeQuantum);
                                 roundRobinScheduling(n, arrival, burst, timeQuantum, completion);
                                     calculateTimes(n, arrival, burst, completion, waiting, turnaround);
                                         displayResults(n, arrival, burst, completion, waiting, turnaround);

                                             return 0;
                                             }

                                             // Function to read arrival times, burst times, and time quantum
                                             void inputData(int n, int arrival[], int burst[], int *timeQuantum) {
                                                 for (int i = 0; i < n; i++) {
                                                         printf("Enter arrival time for process P%d: ", i + 1);
                                                                 scanf("%d", &arrival[i]);
                                                                         printf("Enter burst time for process P%d: ", i + 1);
                                                                                 scanf("%d", &burst[i]);
                                                                                     }
                                                                                         printf("Enter time quantum: ");
                                                                                             scanf("%d", timeQuantum);
                                                                                             }

                                                                                             // Function to perform Round Robin scheduling
                                                                                             void roundRobinScheduling(int n, int arrival[], int burst[], int timeQuantum, int completion[]) {
                                                                                                 int remBurst[n];
                                                                                                     for (int i = 0; i < n; i++) {
                                                                                                             remBurst[i] = burst[i];
                                                                                                                     completion[i] = 0;
                                                                                                                         }

                                                                                                                             int currentTime = 0;
                                                                                                                                 int completed = 0;

                                                                                                                                     while (completed < n) {
                                                                                                                                             bool didSchedule = false;
                                                                                                                                                     for (int i = 0; i < n; i++) {
                                                                                                                                                                 if (arrival[i] <= currentTime && remBurst[i] > 0) {
                                                                                                                                                                                 didSchedule = true;
                                                                                                                                                                                                 if (remBurst[i] > timeQuantum) {
                                                                                                                                                                                                                     currentTime += timeQuantum;
                                                                                                                                                                                                                                         remBurst[i] -= timeQuantum;
                                                                                                                                                                                                                                                         } else {
                                                                                                                                                                                                                                                                             currentTime += remBurst[i];
                                                                                                                                                                                                                                                                                                 remBurst[i] = 0;
                                                                                                                                                                                                                                                                                                                     completion[i] = currentTime;
                                                                                                                                                                                                                                                                                                                                         completed++;
                                                                                                                                                                                                                                                                                                                                                         }
                                                                                                                                                                                                                                                                                                                                                                     }
                                                                                                                                                                                                                                                                                                                                                                             }
                                                                                                                                                                                                                                                                                                                                                                                     // If no process was ready, advance time
                                                                                                                                                                                                                                                                                                                                                                                             if (!didSchedule) {
                                                                                                                                                                                                                                                                                                                                                                                                         currentTime++;
                                                                                                                                                                                                                                                                                                                                                                                                                 }
                                                                                                                                                                                                                                                                                                                                                                                                                     }
                                                                                                                                                                                                                                                                                                                                                                                                                     }

                                                                                                                                                                                                                                                                                                                                                                                                                     // Function to calculate waiting and turnaround times
                                                                                                                                                                                                                                                                                                                                                                                                                     void calculateTimes(int n, int arrival[], int burst[], int completion[], int waiting[], int turnaround[]) {
                                                                                                                                                                                                                                                                                                                                                                                                                         for (int i = 0; i < n; i++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                 turnaround[i] = completion[i] - arrival[i];
                                                                                                                                                                                                                                                                                                                                                                                                                                         waiting[i] = turnaround[i] - burst[i];
                                                                                                                                                                                                                                                                                                                                                                                                                                             }
                                                                                                                                                                                                                                                                                                                                                                                                                                             }

                                                                                                                                                                                                                                                                                                                                                                                                                                             // Function to display process metrics and averages
                                                                                                                                                                                                                                                                                                                                                                                                                                             void displayResults(int n, int arrival[], int burst[], int completion[], int waiting[], int turnaround[]) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                 printf("\nProcess\tArrival\tBurst\tCompletion\tWaiting\tTurnaround\n");
                                                                                                                                                                                                                                                                                                                                                                                                                                                     float totalWait = 0, totalTurnaround = 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                         for (int i = 0; i < n; i++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                 printf("P%d\t%d\t%d\t%d\t\t%d\t\t%d\n", 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                i + 1, arrival[i], burst[i], completion[i], waiting[i], turnaround[i]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        totalWait += waiting[i];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                totalTurnaround += turnaround[i];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        printf("\nAverage waiting time: %.2f\n", totalWait / n);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            printf("Average turnaround time: %.2f\n", totalTurnaround / n);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            